### ISSUE TITLE
Wrong definition of of Issue's StatusDetails property

### ISSUE THREAD

**Issue by grongor** [atlassian/go-sentry-api#11]
See: https://github.com/getsentry/sentry/blob/223c15dc197eeb2ef1941e62b4bb86c0de556050/src/sentry/api/serializers/models/group.py#L260

It's quite a complicated struct, not just simple map.

**Comment by quantonganh** [comment]
>"errorVerbose": "json: cannot unmarshal number into Go struct field Issue.statusDetails of type string
